language: php

php: [5.5, 5.6, hhvm]

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - curl -sS http://bldr.io/installer | php

script:
    - ./bldr.phar build -p travis

notifications:
    mail: "keith@op3nvoice.com"
